### ISSUE TITLE
YOLOv8 Deployment - RPi4

### ISSUE THREAD

**Issue by baqwas** [baqwas/yolov8#1]
```
INFO: pip is looking at multiple versions of opt-einsum to determine which version is compatible with other requirements. This could take a while.
Collecting opt-einsum>=2.3.2
  Downloading https://www.piwheels.org/simple/opt-einsum/opt_einsum-3.2.1-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.5/63.5 kB 387.3 kB/s eta 0:00:00
ERROR: Exception:
Traceback (most recent call last):
  File "/home/chowkidar/projects/yolov8/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/chowkidar/projects/yolov8/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chowkidar/projects/yolov8/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/chowkidar/projects/yolov8/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/home/chowkidar/projects/yolov8/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chowkidar/projects/yolov8/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 392, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
```

**Comment by baqwas** [comment]
Need to re-run the following installation step:
`pip install ultralytics[export]`
